--- #YAML:1.0
name:               WWW-HostipInfo
version:            0.1
abstract:           access to hostip.info API
author:
    - Makamaka Hannyaharamitu (makamaka[at]cpan.org)
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:         0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
